name: Bridge update work

on:
  # 매 15시 0분에 실행
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  Add-Data:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
             
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Firebase credentials
        id: create-json
        uses: jsdaniell/create-json@v1.2.3
        with:
          name: "firebaseKey.json"
          json: ${{ secrets.FIREBASE_KEY }}

      - name: Add data
        run: |
          python update_firebase_b.py
        env:
          DATA_GO_KR_API_KEY: ${{ secrets.BRIDGEKEY }}
